"""update embedding dims

Revision ID: 4fba5d79f993
Revises: 0b65f52c1eb7
Create Date: 2024-01-25 21:21:36.418032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fba5d79f993'
down_revision: Union[str, None] = '0b65f52c1eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddings', 'content')
    # ### end Alembic commands ###
