"""update embedding dims

Revision ID: 5b57f2ec9428
Revises: 45a2fb5f3137
Create Date: 2024-01-25 20:54:27.687748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '5b57f2ec9428'
down_revision: Union[str, None] = '45a2fb5f3137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embeddings', 'vector',
               existing_type=pgvector.sqlalchemy.Vector(dim=1600),
               type_=pgvector.sqlalchemy.Vector(dim=5000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embeddings', 'vector',
               existing_type=pgvector.sqlalchemy.Vector(dim=5000),
               type_=pgvector.sqlalchemy.Vector(dim=1600),
               existing_nullable=True)
    # ### end Alembic commands ###
